# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170324_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ImageProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
